version: '3'
services:

  postgres:
    image: postgres:12.3-alpine
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: adat_db
    volumes:
      - postgresdb:/var/lib/postgresql/data
    ports:
      - 8001:5432

  ada-t-backend:
    build: ./backend
    depends_on:
      - postgres
    container_name: ada-t-backend
    volumes:
      - ./backend:/code
      # - ./backend/database/utilities/ai_model:/code/database/utilities/ai_model
      # - ./backend/alembic:/code/alembic
      # - ./backend/alembic.ini:/code/alembic.ini
    ports:
      - 8002:8000

  # ada-t-frontend:
  #   build: ./frontend/narrator
  #   container_name: ada-t-frontend
  #   volumes:
  #     - ./frontend/narrator:/app
  #   ports:
  #     - 8080:8080
  #   links:
  #     - ada-t-backend

volumes:
  postgresdb: