version: '3'
services:

  ada-t-backend:
    build: ./backend
    container_name: ada-t-backend
    volumes:
      - ./backend/database/utilities/ai_model:/code/database/utilities/ai_model
      - ./backend/alembic:/code/alembic
      - ./backend/alembic.ini:/code/alembic.ini
    ports:
      - 8000:8000

  ada-t-frontend:
    build: ./frontend/narrator
    container_name: ada-t-frontend
    ports:
      - 8080:8080
    links:
      - ada-t-backend