"""empty message

Revision ID: c775ba853782
Revises: b3634fd01ef1
Create Date: 2024-02-09 14:32:01.779441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c775ba853782'
down_revision: Union[str, None] = 'b3634fd01ef1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('projects', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('projects', 'create_uid',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('projects', 'create_date',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('projects', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('projects', 'create_date',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('projects', 'create_uid',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('projects', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_table('questions')
    # ### end Alembic commands ###
